defmodule BabyNames.Repo.Collaboration do
  use Ecto.Schema
  import Ecto.Changeset


  schema "collaborations" do
    # token autogenerated in db
    field :token, Ecto.UUID
    field :owner_id, :id
    field :holder_id, :id

    timestamps()
  end

  @doc false
  def changeset(collaboration, attrs) do
    collaboration
    |> cast(attrs, [:owner_id])
    |> foreign_key_constraint(:owner_id, message: "owner doesn't exist")
    |> validate_required([:owner_id])
  end

  @doc false
  def connect_changeset(collaboration, attrs) do
    collaboration
    |> cast(attrs, [:holder_id])
    |> foreign_key_constraint(:holder_id, message: "holder doesn't exist")
    |> validate_required([:holder_id])
  end
end
