defmodule BabyNames.Repo.Collaboration do
  use Ecto.Schema
  import Ecto.Changeset


  schema "collaborations" do
    # token autogenerated in db
    field :token, Ecto.UUID
    field :owner_id, :id
    field :holder_id, :id

    timestamps()
  end

  @doc false
  def changeset(collaboration, attrs) do
    collaboration
    |> cast(attrs, [:owner_id, :holder_id])
    |> validate_required([:owner_id, :holder_id])
  end
end
